name: Code Coverage

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      - run: composer install --no-progress

      - run: |
          vendor/bin/phpunit --coverage-clover build/logs/clover.xml
          # coveralls.io
          wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
          php php-coveralls.phar --verbose
        env:
          COVERALLS_REPO_TOKEN: 'aGNZHzlw8nPDYMznWOS7DVbfaN6BRxBnn'
