name: Monorepo Validate

on:
  pull_request: null
  push:
    branches:
      - master
jobs:
  monorepo_validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - run: composer install --no-progress
      - run: /vendor/bin/monorepo-builder validate
