name: 'PR title'
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: dylanvann/check-pull-request-title@v1
        with:
          # Match pull request titles in the form "[Package] - Message".
          pattern: '^\[[A-Z][a-z]{3,}\] - .+'
      - uses: morrisoncole/pr-lint-action@v1.0.0
        with:
          # Match pull request titles in the form "[Package] - Message"
          title-regex: "\[[A-Z][a-z]{3,}\] - .+"
          on-failed-regex-comment: "Pull request title must be in de form: \"[Package] - Message\""
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
