name: 'PR lint'
on:
  pull_request:
    types: [ opened, edited, reopened ]

jobs:
  pr_title_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.3.0
        with:
          # Match pull request titles in the form "[Package] Pull request description"
          title-regex: '^\[[A-Z][a-z]{2,}\]\s.+'
          on-failed-regex-comment: "Pull request title must be in de form: \"[Package] Pull request description\" (%regex%)"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
