name: 'PR lint'
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize

jobs:
  pr_title_lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: morrisoncole/pr-lint-action@v1.0.0
        with:
          # Match pull request titles in the form "[Package] Pull request description"
          title-regex: '^\[[A-Z][a-z]{2,}\]\s.+'
          on-failed-regex-comment: "Pull request title must be in de form: \"[Package] Pull request description\" (%regex%)"
