name: Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4' ]

    name: Run tests for PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPUnit
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/logs/clover.xml

