name: Test Coverage

on:
  push:
    branches:
      - master
      - bugfix/coveralls-io

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=100000 origin

      - uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          coverage: pcov

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      - run: composer install --prefer-dist --no-progress --no-suggest

      - run: |
          vendor/bin/phpunit --coverage-clover coverage.xml

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
